### ISSUE TITLE
Implement `transferWithPermit`

### ISSUE THREAD

**Issue by offerijns** [centrifuge/liquidity-pools#48]
Similar to https://github.com/centrifuge/tinlake/blob/main/src/lender/operator.sol#L150

**Comment by mustermeiszer** [comment]
When is this needed? Connectors v2 already?

**Comment by offerijns** [comment]
I guess v3 is fine. It's a significant UX improvement (requiring 1 rather than two tx signatures). I would combine it when we do https://github.com/centrifuge/connectors/issues/18
